# Generated by Django 2.2.16 on 2022-06-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220620_2009'),
        ('users', '0002_auto_20220620_1723'),
    ]

    operations = [
    ]
