# Generated by Django 2.2.16 on 2022-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20220621_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='confirmation code'),
        ),
    ]
