# Generated by Django 2.2.16 on 2022-06-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220621_1417'),
        ('api', '0002_auto_20220621_1033'),
    ]

    operations = [
    ]
