# Generated by Django 2.2.16 on 2022-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20220623_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
