# Generated by Django 2.2.16 on 2022-06-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_title_description'),
        ('actions', '0003_auto_20220623_2108'),
    ]

    operations = [
    ]
