# Generated by Django 2.2.16 on 2022-06-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20220624_0958'),
        ('actions', '0005_auto_20220624_1651'),
    ]

    operations = [
    ]
