# Generated by Django 2.2.16 on 2022-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_merge_20220624_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
