# Generated by Django 2.2.16 on 2022-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20220625_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
