# Generated by Django 2.2.16 on 2022-06-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_merge_20220624_1454'),
        ('actions', '0011_auto_20220625_1150'),
    ]

    operations = [
    ]
