# Generated by Django 2.2.16 on 2022-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_merge_20220625_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
