# Generated by Django 2.2.16 on 2022-06-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_auto_20220625_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
