# Generated by Django 2.2.16 on 2022-06-25 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_auto_20220625_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Category'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title_genre', through='actions.GenreTitle', to='actions.Genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-2000), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
